### ISSUE TITLE
Where can I download this file torch-0.3.0b0+9622eaa-cp27-cp27m-macosx_10_12_intel.whl?

### ISSUE THREAD

**Issue by ruizewang** [TomHeaven/pytorch-osx-build#1]
Hello,
I can't find older releases (torch 0.3) in the releases page.

**Comment by TomHeaven** [comment]
You can find the repo here: [https://github.com/TomHeaven/pytorch-osx-build/tree/a19f287b827ab290b62c9c5c1997eacc294a0fec](https://github.com/TomHeaven/pytorch-osx-build/tree/a19f287b827ab290b62c9c5c1997eacc294a0fec)

This is not a stable release so I didn't expect someone will need it.

**Comment by ruizewang** [comment]
Ok, thank you :)
