### ISSUE TITLE
anaconda env settings

### ISSUE THREAD

**Issue by c66tang** [TomHeaven/pytorch-osx-build#12]
Hi, thanks for sharing these packages.

I installed both latest tensorflow and pytorch releases in two separate Anaconda envs. The tensorflow works great out-of-the-box, but the pytorch has import errors. Any suggestions?

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/torch16-osx/lib/python3.7/site-packages/torch/__init__.py", line 188, in <module>
    _load_global_deps()
 File "/opt/anaconda3/envs/torch16-osx/lib/python3.7/site-packages/torch/__init__.py", line 141, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
 File "/opt/anaconda3/envs/torch16-osx/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
 OSError: dlopen(/opt/anaconda3/envs/torch16-osx/lib/python3.7/site-packages/torch/lib/libtorch_global_deps.dylib, 10): 
 Library not loaded: @rpath/libcurand.10.0.dylib
  Referenced from: /opt/anaconda3/envs/torch16-osx/lib/python3.7/site-packages/torch/lib/libtorch_global_deps.dylib
  Reason: image not found`

I have already added the following environment settings,
_export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$CUDA_HOME/lib:$CUDA_HOME/nvvm/lib:$CUDA_HOME/extras/$
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
export PATH=$CUDA_HOME/bin:$PATH_

**Comment by TomHeaven** [comment]
It is clear that your cuda libraries is missing from your library paths.
If setting `DYLD_LIBRARY_PATH` does not work, try setting `DYLD_FALLBACK_LIBRARY_PATH` instead such as
```
export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_FALLBACK_LIBRARY_PATH
```

**Comment by c66tang** [comment]
Thanks for the reply. I tried but no luck. I will go with the homebrew install.
