### ISSUE TITLE
Do you still want to crack tensorflow's future version?

### ISSUE THREAD

**Issue by llv22** [TomHeaven/pytorch-osx-build#16]
curious, would you? or for CUDA 11 and further cudnn support?

**Comment by TomHeaven** [comment]
CUDA 10.2 is the last CUDA version that supports macOS. Therefore, forget about CUDA 11 unless someday Apple start to use Nvidia's chip again.

I'll try to support both TF and Pytorch on macOS 10.13.6 / CUDA 10.1 / CUDNN 7.6.5 as long as I can.

**Comment by llv22** [comment]
@TomHeaven thanks, let me know when you start. I'm curious about how to adapt source code with macOS 10.13.6 / CUDA 10.1 / CUDNN 7.6.5. perhaps I can do something as well.
