### ISSUE TITLE
About tensorpipe enablement with torch 1.11.0/1.12.0

### ISSUE THREAD

**Issue by llv22** [TomHeaven/pytorch-osx-build#20]
@TomHeaven Just for your information, I also cracked torch 1.11.0/1.12.0 for the same environment as you targeted at. And the key to enable tensorpipe on macOS 10.13.6 is to rewrite parts of code in https://github.com/llv22/tensorpipe-macos-cuda/blob/main/tensorpipe/common/dl.h to avoid use linux header files <link.h> and use ::dladdr to replace ::dlinfo. Not a big deal, but it can make tensorpipe available for torch. 
I will try to ask tensorpipe dev whether not this feature can be adapted in the later version. 

release link: https://github.com/llv22/pytorch-macOS-cuda/releases
Best Regards
Orlando

**Comment by TomHeaven** [comment]
Great! I'll try that in the next release.

**Comment by llv22** [comment]
@TomHeaven If there is any issue, please let me via github.com ticket or my gmail xiandao.airs@gmail.com. ^-^ The good news is that there seems no hard requirements of Torch to leverage new features of CUDA 10.2+. So we can still crack along our previous way until Nvidia and Apple would finish their deal ^-^

**Comment by TomHeaven** [comment]
The fix is adopted in the v2.0.0 release.

**Comment by TomHeaven** [comment]
Closed.
