### ISSUE TITLE
增加python 3.6版本的wheel

### ISSUE THREAD

**Issue by helloall1900** [TomHeaven/pytorch-osx-build#4]
使用anaconda安装torch-1.0-cp37-cp37m-macosx_10_12_x86_64.whl，提示：

`
torch-1.0-cp37-cp37m-macosx_10_12_x86_64.whl is not a supported wheel on this platform.
`

anaconda环境python最新版本是3.6，所以无法安装，能不能添加cp36版本whl

**Comment by TomHeaven** [comment]
已添加py36版本到release。
