### ISSUE TITLE
Add build for Cuda 10.1

### ISSUE THREAD

**Issue by burgalon** [TomHeaven/pytorch-osx-build#7]
Any chance to add build for CUDA 10.1? 
Thanks

**Comment by TomHeaven** [comment]
10.1 is a temporary version of CUDA and not within my support plan.  Please use CUDA 10.0 or build yourself according to the tutorial: https://github.com/TomHeaven/pytorch-osx-build/blob/master/BuildInstractions-1.0.1.md.
