### ISSUE TITLE
请问你遇到过mac上运行cuda应用系统卡死的问题么？

### ISSUE THREAD

**Issue by desert0616** [TomHeaven/pytorch-osx-build#9]
你好，想咨询一个跟本仓库无关的问题。你遇到过在mac上运行cuda会导致系统卡死的问题么？是否有相关经验来排查和解决这个问题？

我目前的状况是当运行cuda程序是，系统会随机卡死，一般发生在执行training 4-5小时的时间点。如不执行cuda程序，则没有这个问题。

我的配置：
x99+6800K+1080ti
10.13.6

谢谢

**Comment by TomHeaven** [comment]
会有偶发死机的情况，尤其是显存紧张时，在图形界面上频繁操作可能导致死机。但是这个频率不应该很高。如果你每次都能遇到可能是程序显存占用太极限了，那就跑程序的时候不要操作机器，或者减少显存占用。
